# Generated by Django 5.1.7 on 2025-04-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalentity',
            name='parent_location',
        ),
    ]
