# Generated by Django 5.1.7 on 2025-03-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_total_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_flashback_character',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
