# Generated by Django 5.1.7 on 2025-04-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_politicalentity_parent_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='character',
            new_name='api_charact_politic_61712e_idx',
            old_name='api_charact_politic_0743fd_idx',
        ),
        migrations.AlterField(
            model_name='character',
            name='political_entity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
