# Generated by Django 5.1.7 on 2025-04-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_charact_politic_0743fd_idx_api_charact_politic_61712e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalentity',
            name='entity_type',
            field=models.CharField(choices=[('nation', 'Nation'), ('unclaimed_land', 'Unclaimed Land'), ('city', 'City'), ('city_state', 'City State'), ('ocean', 'Ocean'), ('continent', 'Continent'), ('region', 'Region'), ('village', 'Village'), ('fortress', 'Fortress'), ('island', 'Island'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiantpower',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='api.radiantorder'),
        ),
    ]
