# Generated by Django 5.1.7 on 2025-03-14 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_main_flashback_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='main_flashback_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_as_flashback', to='api.character'),
        ),
    ]
