# Generated by Django 5.1.7 on 2025-04-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_politicalentity_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiantpower',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiant_powers', to='api.radiantorder'),
        ),
    ]
