# Generated by Django 5.1.7 on 2025-04-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_radiantpower_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='part',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
