# Generated by Django 5.1.7 on 2025-04-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chapter_part'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
